import { API } from '../api.js';

export async function openExplainModal(topic, context = {}, defaultTitle = 'AI Reasoning & Decision Rationale') {
  let modal = document.getElementById('explain-modal');
  if (!modal) {
    modal = document.createElement('div');
    modal.id = 'explain-modal';
    modal.className = 'fixed inset-0 z-[99999] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm';
    document.body.appendChild(modal);
  }

  modal.innerHTML = `
    <div class="glass-card bg-slate-900/95 border border-purple-500/30 rounded-2xl w-full max-w-lg overflow-hidden shadow-2xl p-6 relative animate-in fade-in zoom-in-95 duration-200">
      <div class="flex items-center justify-between pb-4 border-b border-slate-800">
        <div class="flex items-center gap-2.5">
          <div class="w-8 h-8 rounded-lg bg-purple-600/20 border border-purple-500/30 flex items-center justify-center text-purple-400">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
          </div>
          <div>
            <h3 class="text-base font-bold text-white">${defaultTitle}</h3>
            <span class="text-xs text-purple-400 font-mono">Agentic Explainability Engine</span>
          </div>
        </div>
        <button id="close-explain-btn" class="w-7 h-7 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 flex items-center justify-center text-lg leading-none transition">×</button>
      </div>

      <div class="py-5" id="explain-content-body">
        <div class="flex items-center justify-center py-8 gap-3 text-slate-400 text-sm">
          <svg class="animate-spin h-5 w-5 text-purple-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z"></path></svg>
          Synthesizing multi-agent consensus rationale...
        </div>
      </div>

      <div class="flex items-center justify-between pt-4 border-t border-slate-800 text-xs text-slate-400">
        <span class="flex items-center gap-1.5">
          <span class="w-2 h-2 rounded-full bg-emerald-500"></span> Deterministic Hard-Constraint Verified
        </span>
        <button id="close-explain-footer-btn" class="px-4 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 font-medium transition">Close</button>
      </div>
    </div>
  `;

  modal.classList.remove('hidden');

  const close = () => modal.classList.add('hidden');
  document.getElementById('close-explain-btn').onclick = close;
  document.getElementById('close-explain-footer-btn').onclick = close;

  try {
    const res = await API.explainDecision(topic, context);
    const body = document.getElementById('explain-content-body');
    body.innerHTML = `
      <div class="bg-purple-950/20 border border-purple-500/20 rounded-xl p-4 mb-4">
        <div class="text-xs font-semibold text-purple-300 uppercase tracking-wider mb-1.5">Consensus Rationale</div>
        <p class="text-slate-200 text-sm leading-relaxed">${res.explanation}</p>
      </div>
      <div class="grid grid-cols-2 gap-2 text-xs">
        <div class="bg-slate-800/60 p-2.5 rounded-lg border border-slate-700/50">
          <span class="text-slate-400 block text-[10px] uppercase font-mono">Validation Engine</span>
          <span class="text-emerald-400 font-semibold">Constraint Collision Safe</span>
        </div>
        <div class="bg-slate-800/60 p-2.5 rounded-lg border border-slate-700/50">
          <span class="text-slate-400 block text-[10px] uppercase font-mono">Agent Mode</span>
          <span class="text-purple-400 font-semibold">${res.mode || 'Active'}</span>
        </div>
      </div>
    `;
  } catch (err) {
    document.getElementById('explain-content-body').innerHTML = `
      <p class="text-sm text-slate-300">${context.fallback || 'Recommendation generated by automated multi-agent constraint evaluation and capacity ranking.'}</p>
    `;
  }
}
